### PR TITLE
use groups to identify access

### LINKED ISSUE #7: Roles mapping doesn't work
When connecting with a user that has admin role on the related namespace I get empty roles array.
I think that it is related to the way findUserRoles works specifically the subject access review request.

This is the logs I get on DEBUG level
```
2019.09.23 17:03:54 DEBUG web[AW1e/gXPPr9iPlvgAAGW][c.r.s.a.o.OpenShiftConfiguration] API url: https://172.30.0.1:443/
2019.09.23 17:03:54 DEBUG web[AW1e/gXPPr9iPlvgAAGW][c.r.s.a.o.OpenShiftIdentityProvider] SAR body {"kind":"SubjectAccessReview","apiVersion":"v1","namespace":"sonarqube","verb":"admin","resourceAPIGroup":"","resourceAPIVersion":"","resource":"sonarqube","resourceName":"","user":"","groups":[],"scopes":[]}
2019.09.23 17:03:54 DEBUG web[AW1e/gXPPr9iPlvgAAGW][s.n.w.p.h.HttpURLConnection] sun.net.www.MessageHeader@5a97ee1a8 pairs: {POST /oapi/v1/subjectaccessreviews HTTP/1.1: null}{Authorization: Bearer MASKED}{Content-Type: application/json}{User-Agent: Java/1.8.0_181}{Host: 172.30.0.1}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}{Content-Length: 208}
2019.09.23 17:03:54 DEBUG web[AW1e/gXPPr9iPlvgAAGW][s.n.w.p.h.HttpURLConnection] sun.net.www.MessageHeader@cc19f05 pairs: {null: HTTP/1.1 201 Created}{Cache-Control: no-store}{Content-Type: application/json}{Date: Mon, 23 Sep 2019 17:03:54 GMT}{Content-Length: 198}
2019.09.23 17:03:54 DEBUG web[AW1e/gXPPr9iPlvgAAGW][c.r.s.a.o.OpenShiftIdentityProvider] SAR body {"kind":"SubjectAccessReview","apiVersion":"v1","namespace":"sonarqube","verb":"edit","resourceAPIGroup":"","resourceAPIVersion":"","resource":"sonarqube","resourceName":"","user":"","groups":[],"scopes":[]}
2019.09.23 17:03:54 DEBUG web[AW1e/gXPPr9iPlvgAAGW][s.n.w.p.h.HttpURLConnection] sun.net.www.MessageHeader@78af83a88 pairs: {POST /oapi/v1/subjectaccessreviews HTTP/1.1: null}{Authorization: Bearer MASKED}{Content-Type: application/json}{User-Agent: Java/1.8.0_181}{Host: 172.30.0.1}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}{Content-Length: 207}
2019.09.23 17:03:54 DEBUG web[AW1e/gXPPr9iPlvgAAGW][s.n.w.p.h.HttpURLConnection] sun.net.www.MessageHeader@18cc16d45 pairs: {null: HTTP/1.1 201 Created}{Cache-Control: no-store}{Content-Type: application/json}{Date: Mon, 23 Sep 2019 17:03:54 GMT}{Content-Length: 197}
2019.09.23 17:03:54 DEBUG web[AW1e/gXPPr9iPlvgAAGW][c.r.s.a.o.OpenShiftIdentityProvider] SAR body {"kind":"SubjectAccessReview","apiVersion":"v1","namespace":"sonarqube","verb":"view","resourceAPIGroup":"","resourceAPIVersion":"","resource":"sonarqube","resourceName":"","user":"","groups":[],"scopes":[]}
2019.09.23 17:03:54 DEBUG web[AW1e/gXPPr9iPlvgAAGW][s.n.w.p.h.HttpURLConnection] sun.net.www.MessageHeader@482dce7b8 pairs: {POST /oapi/v1/subjectaccessreviews HTTP/1.1: null}{Authorization: Bearer MASKED}{Content-Type: application/json}{User-Agent: Java/1.8.0_181}{Host: 172.30.0.1}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}{Content-Length: 207}
2019.09.23 17:03:54 DEBUG web[AW1e/gXPPr9iPlvgAAGW][s.n.w.p.h.HttpURLConnection] sun.net.www.MessageHeader@4c9bb6155 pairs: {null: HTTP/1.1 201 Created}{Cache-Control: no-store}{Content-Type: application/json}{Date: Mon, 23 Sep 2019 17:03:54 GMT}{Content-Length: 197}
2019.09.23 17:03:54 DEBUG web[AW1e/gXPPr9iPlvgAAGW][c.r.s.a.o.OpenShiftIdentityProvider] Roles []
```
When I tried to post the SAR json from the logs using postman I get this response:
```
{
  "kind": "SubjectAccessReviewResponse",
  "apiVersion": "v1",
  "namespace": "sonarqube",
  "allowed": false,
  "reason": "User \"developer\" cannot \"admin\" \"sonarqube\" with name \"\" in project \"sonarqube\""
}
```

### PR DESCRIPTION
**Pull request by mcanoy**
Resolves #7 

The implementation of roles did not work properly and was masked by testing with users with elevated privileges. 

Now Openshift GROUPS will be mapped to Sonarqube roles. Groups are avaliable when calling the user api. 

From the info in the readme: 

This plugin will map OpenShift groups to Sonarqube roles. These values are set with the property

```
sonar.auth.openshift.sar.groups=ocp-admin=sonar-administrators,ocp-users=sonar-users
```

This shows that Sonarqube will allow OpenShift users who are in the group ocp-admin users to be administrators with the role of sonar-administrators. Ordinary users will be added as sonar-users if they are OpenShift users in the group ocp-users. These OpenShift groups do not exist by default.

The default mapping value is:

```
sonar.auth.openshift.sar.groups=sonar-administrators=sonar-administrators,sonar-users=sonar-users
```

### CODE REVIEW

File: src/test/java/com/rhc/sonarqube/auth/openshift/test/MockHttpClient.java [hunk 1]
```diff
@@ -46,8 +46,8 @@ public void close() throws IOException {
 	@Override
 	public Response execute(String userAgent, Map<String, String> headers, Verb httpVerb, String completeUrl,
 			byte[] bodyContents) throws InterruptedException, ExecutionException, IOException {
-		
-		if(completeUrl.contentEquals("http://127.0.0.1/oapi/v1/users/~")) {
+
+		if(completeUrl.contentEquals("http://127.0.0.1/apis/user.openshift.io/v1/users/~")) {
```
Comment (InfoSec812) [inline src/test/java/com/rhc/sonarqube/auth/openshift/test/MockHttpClient.java:50]: This API endpoint is very OpenShift specific. Would it be possible to make it more generic to Kubernetes, or would that be a functionality beyond what native K8s provides?

Comment (mcanoy) [reply src/test/java/com/rhc/sonarqube/auth/openshift/test/MockHttpClient.java:50]: There really isn't. The first url I was using was still OpenShift specific but the whole implementation was not correct. Kube has an authorization API but it requires giving access to cluster resources. So, if I wanted it to work with that API I would have to make an api call that would be like:

Can user1 view pods (great you're a sonar user)
Can user1 create pods (great you're a sonar admin)

I am thinking that approach requires too much cluster access. Also, differentiating user and admin access would be awkward. Instead using the group approach - a group can be created specifically for the application and sonar queries user information for groups that the user belongs to. Here - the user can essentially have access to nothing in OpenShift and still use and administer Sonarqube
